name: 'Sonar Scanner'
description: 'Executar o Sonar Scanner e Publicar o Resultado'
author: 'Alex de Souza Silva'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  projectKey:  # id of input
    description: 'Project Key'
    required: true
    default: 'test-scan'
  sources:  # id of input
    description: 'Source'
    required: true
    default: 'src'
  url:  # id of input
    description: 'URL'
    required: true
    default: 'http://localhost:9000'
  version:  # id of input
    description: 'Version'
    required: true
    default: '0.0.1-sc'
  binaries:  # id of input
    description: 'Binaries'
    required: true
    default: '.'
  password:  # id of input
    description: 'Password'
    required: true
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.projectKey }}
    - ${{ inputs.sources }}
    - ${{ inputs.url }}
    - ${{ inputs.version }}
    - ${{ inputs.binaries }}
    - ${{ inputs.password }}
    
